### ISSUE TITLE
KeyError: 'P' in pandas when running test data with HARE

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [ossmith/HARE#2]
Dear author,

Firstly, thank you for developing this wonderful tool. I encountered an issue while testing it using the provided code, which is the same as in your tutorial. Here is the code:
```shell
hare intersect -g example_files/exampleGWAS.tsv -e reference_assets/harsRichard2020.GRCh37.bed -r reference_assets/UCSC.GRCh37.autosomes.annotation.bed -n 100 --cache_dir /gpfs/home/zhangyue/.vep --cache_version 105 -o hare.test
```
However, I encountered the following error:
```shell

 ----------------------------------------------------------------------
|                                                                      |
|      Welcome to the HARE genetic feature enrichment pipeline.        |
|  Please contact Olivia Smith at osmith@utexas.edu to report issues.  |
|                                                                      |
 ----------------------------------------------------------------------

-----Workflow started at 2023-12-22 12:39:25.885827.

[args] GWAS summary statistics file: 'example_files/exampleGWAS.tsv'
[args] P-value significance threshold: 1e-06
[args] Minor allele frequency (MAF) threshold: 0.01
[args] VEP cache directory: '/gpfs/home/zhangyue/.vep', version 105
[args] Annotation max distance: 5000
[args] Biotypes included in analysis: protein_all
[args] Reference genome annotation file: 'reference_assets/UCSC.GRCh37.autosomes.annotation.bed'
[args] Reference genome build: GRCh37
[args] Element of interest BED file: 'reference_assets/harsRichard2020.GRCh37.bed'
[args] Simulation draws to be performed: 100
[args] Results will be written to hare.test.*
Loading GWAS summary statistics...OK
OK
Filtering SNPs for analysis...Traceback (most recent call last):
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'P'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/bin/hare", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/hare.py", line 83, in main
    run_intersect(intargs)
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/hare.py", line 30, in run_intersect
    intersect.main(**intersect_args)
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/intersect.py", line 591, in main
    snps_filepath = gwas_import(hareParameters, hareSettings)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/intersect.py", line 231, in gwas_import
    gwas_df[argumentClass.p_col] = gwas_df[argumentClass.p_col].replace(to_replace=list([NaN,"-"]),value=1)
                                   ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/gpfs/home/zhangyue/anaconda3/envs/hare-env/lib/python3.11/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'P'
```
It seems like there is an issue with the 'P' key. Could you please help me understand what is happening?

Thanks in advance, and I hope to receive your early reply.

Gemma

**Comment by ossmith** [comment]
Hi Gemma,

Thanks for catching this! Looks like the command in my instructions is missing a flag -- you should be able to correct this by adding `--source_bolt`.

EDIT: Just realized I also made a modification during development that makes this mismatch the P column still, so I've uploaded a new version of the exampleGWAS.tsv file to address it.

We are going to do a new release very soon (within the next week ideally) and I will respond here to let you know once that's been pushed, which should also take care of this issue.

Olivia

**Comment by Gemma-Zhang-326** [comment]
Hi @ossmith ,

I'm very excited to hear about the news of your upcoming new release. I will continue to follow this work closely. Thank you so much for your kind and prompt reply.

Yours sincerely,
Gemma

**Comment by ossmith** [comment]
Hi Gemma,

Wanted to update you that the new release is out today :)

Best,
Olivia

**Comment by Gemma-Zhang-326** [comment]
> Hi Gemma,
> 
> Wanted to update you that the new release is out today :)
> 
> Best, Olivia

Hi Olivia,
Thank you for your kind information, Very excited to know this good news. I would try this new version in my research work.

Thanks for all the effort you have done.

Yours,
Gemma
